name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/myimage
    - name: Images present
      run: docker images
    - name: Running a Docker Image
      run: docker run -p 3000:3000 -d ${{ secrets.DOCKERHUB_USERNAME }}/myimage
    - name: Containers present
      run: docker ps -a
    - name: Login to DockerHub
      run: docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" -p="${{ secrets.DOCKERHUB_PASSWORD }}"
    - name: Pushing Docker Image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myimage
    - name: Uploading an Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myartifact
        path: ${{ github.workspace }}
    - name: Creating Object
      run: kubectl apply -f deployment.yml
    - name: Checking Deployment
      run: kubectl get deployment
    - name: Getting Pods
      run: kubectl get pods
    - name: Creating Service
      run: kubectl apply -f service.yml
    - name: Node service created
      run: kubectl get svc
